#encoding: utf-8

TEAMS = [
    {'name': 'Real Madrid', 'country': 'Spa', 'color': 'White'}, 
    {'name': 'FC Barcelona', 'country': 'Spa', 'color': 'Blue'}, 
    {'name': 'Atlético Madrid', 'country': 'Spa', 'color': 'Red'}, 
    {'name': 'Bayern München', 'country': 'Ger', 'color': 'Red'}, 
    {'name': 'Juventus', 'country': 'Ita', 'color': 'Black'}, 
    {'name': 'Sevilla', 'country': 'Spa', 'color': 'Red'}, 
    {'name': 'PSG', 'country': 'Fra', 'color': 'Blue'}, 
    {'name': 'Man. City', 'country': 'Eng', 'color': 'Blue'}, 
    {'name': 'Arsenal', 'country': 'Eng', 'color': 'Red'}, 
    {'name': 'FC Porto', 'country': 'Por', 'color': 'Blue'}, 
    {'name': 'Shakhtar', 'country': 'Ukr', 'color': 'Orange'}, 
    {'name': 'Dortmund', 'country': 'Ger', 'color': 'Yellow'}, 
    {'name': 'AS Roma', 'country': 'Ita', 'color': 'Red'}, 
    {'name': 'Napoli', 'country': 'Ita', 'color': 'Blue'}, 
    {'name': 'Liverpool', 'country': 'Eng', 'color': 'Red'}, 
    {'name': 'Man. United', 'country': 'Eng', 'color': 'Red'}, 
    {'name': 'Zenit', 'country': 'Rus', 'color': 'Blue'}, 
    {'name': 'Chelsea', 'country': 'Eng', 'color': 'Blue'}, 
    {'name': 'Monaco', 'country': 'Fra', 'color': 'Red'}, 
    {'name': 'Besiktas', 'country': 'Tur', 'color': 'Black'}, 
    {'name': 'Benfica', 'country': 'Por', 'color': 'Red'}, 
    {'name': 'Dinamo Kiev', 'country': 'Ukr', 'color': 'Blue'}, 
    {'name': 'Tottenham', 'country': 'Eng', 'color': 'White'}, 
    {'name': 'Villarreal', 'country': 'Spa', 'color': 'Yellow'}, 
    {'name': 'Basel', 'country': 'Sui', 'color': 'Red'}, 
    {'name': 'Leverkusen', 'country': 'Ger', 'color': 'Red'}, 
    {'name': 'Schalke 04', 'country': 'Ger', 'color': 'Blue'}, 
    {'name': 'Lyon', 'country': 'Fra', 'color': 'Red'}, 
    {'name': 'Ajax', 'country': 'Ned', 'color': 'Red'}, 
    {'name': 'CSKA', 'country': 'Rus', 'color': 'Red'}, 
    {'name': 'Anderlecht', 'country': 'Bel', 'color': 'Purple'}, 
    {'name': 'Athletic Bilbao', 'country': 'Spa', 'color': 'Red'}, 
    {'name': 'Sporting CP', 'country': 'Por', 'color': 'Green'}, 
    {'name': 'FC Salzburg', 'country': 'Aut', 'color': 'Red'}, 
    {'name': 'VfL Wolfsburg', 'country': 'Ger', 'color': 'Green'}, 
    {'name': 'Olympiakos', 'country': 'Gre', 'color': 'Red'}, 
    {'name': 'Fiorentina', 'country': 'Ita', 'color': 'Purple'}, 
    {'name': 'Sparta Praha', 'country': 'Cze', 'color': 'Red'}, 
    {'name': 'PSV Eindhoven', 'country': 'Ned', 'color': 'Red'}, 
    {'name': 'Lazio', 'country': 'Ita', 'color': 'Blue'}, 
    {'name': 'Club Brugge', 'country': 'Bel', 'color': 'Blue'}, 
    {'name': 'Marseille', 'country': 'Fra', 'color': 'Blue'}, 
    {'name': 'Sporting Braga', 'country': 'Por', 'color': 'Red'}, 
    {'name': 'FC København', 'country': 'Den', 'color': 'Blue'}, 
    {'name': 'AA Gent', 'country': 'Bel', 'color': 'Blue'}, 
    {'name': 'Mönchengladbach', 'country': 'Ger', 'color': 'Green'}, 
    {'name': 'Celtic', 'country': 'Sco', 'color': 'Green'}, 
    {'name': 'FK Krasnodar', 'country': 'Rus', 'color': 'Green'}, 
    {'name': 'Viktoria Plzen', 'country': 'Cze', 'color': 'Red'}, 
    {'name': 'Lokomotiv', 'country': 'Rus', 'color': 'Red'}, 
    {'name': 'Fenerbahçe', 'country': 'Tur', 'color': 'Blue'}, 
    {'name': 'Ludogorets', 'country': 'Bul', 'color': 'Green'}, 
    {'name': 'APOEL', 'country': 'Cyp', 'color': 'Blue'}, 
    {'name': 'Young Boys', 'country': 'Sui', 'color': 'Black'}, 
    {'name': 'FK Astana', 'country': 'Kaz', 'color': 'Blue'}, 
    {'name': 'Legia Warsaw', 'country': 'Pol', 'color': 'Black'}, 
    {'name': 'Inter', 'country': 'Ita', 'color': 'Blue'}, 
    {'name': 'Dnipro', 'country': 'Ukr', 'color': 'Blue'}, 
    {'name': 'PAOK', 'country': 'Gre', 'color': 'Black'}, 
    {'name': 'Steaua', 'country': 'Rom', 'color': 'Blue'}, 
    {'name': 'Saint-Étienne', 'country': 'Fra', 'color': 'Green'}, 
    {'name': 'BATE Borisov', 'country': 'Bls', 'color': 'Blue'}, 
    {'name': 'Qarabag', 'country': 'Azb', 'color': 'Black'}, 
    {'name': 'Feyenoord', 'country': 'Ned', 'color': 'Red'}, 
    {'name': 'Leicester', 'country': 'Eng', 'color': 'Blue'}, 
    {'name': 'Galatasaray', 'country': 'Tur', 'color': 'Red'}, 
    {'name': 'RB Leipzig', 'country': 'Ger', 'color': 'Red'}, 
    {'name': 'Dinamo Zagreb', 'country': 'Cro', 'color': 'Blue'}, 
    {'name': 'Rapid Wien', 'country': 'Aut', 'color': 'Green'}, 
    {'name': 'Valencia', 'country': 'Spa', 'color': 'White'}, 
    {'name': 'Racing Genk', 'country': 'Bel', 'color': 'Blue'}, 
    {'name': 'Celta Vigo', 'country': 'Spa', 'color': 'Blue'}, 
    {'name': 'NK Maribor', 'country': 'Slo', 'color': 'Blue'}, 
    {'name': 'Partizan', 'country': 'Srb', 'color': 'Black'}, 
    {'name': 'Real Betis', 'country': 'Spa', 'color': 'Green'}, 
    {'name': 'Real Sociedad', 'country': 'Spa', 'color': 'Blue'},
]

COLORS = [
    {'name': 'Blue', 'hex': '#485C96'}, 
    {'name': 'White', 'hex': '#7E7E7E'}, 
    {'name': 'Red', 'hex': '#B22222'}, 
    {'name': 'Black', 'hex': '#111111'}, 
    {'name': 'Orange', 'hex': '#FF8C00'}, 
    {'name': 'Yellow', 'hex': '#FFD700'}, 
    {'name': 'Purple', 'hex': '#4B0082'}, 
    {'name': 'Green', 'hex': '#228B22'}
]

COUNTRIES = [
    {'id': 'Spa', 'name': 'Spain'}, 
    {'id': 'Ger', 'name': 'Germany'}, 
    {'id': 'Ita', 'name': 'Italy'}, 
    {'id': 'Eng', 'name': 'England'}, 
    {'id': 'Fra', 'name': 'France'},
    {'id': 'Por', 'name': 'Portugal'},
    {'id': 'Cro', 'name': 'Croatia'}, 
    {'id': 'Ned', 'name': 'Netherlands'}, 
    {'id': 'Bel', 'name': 'Belgium'}, 
    {'id': 'Rus', 'name': 'Russia'}, 
    {'id': 'Tur', 'name': 'Turkey'}, 
    {'id': 'Ukr', 'name': 'Ukraine'}, 
    {'id': 'Sui', 'name': 'Switzerland'}, 
    {'id': 'Aut', 'name': 'Austria'}, 
    {'id': 'Gre', 'name': 'Greece'}, 
    {'id': 'Cze', 'name': 'Czech Republic'}, 
    {'id': 'Den', 'name': 'Denmark'}, 
    {'id': 'Sco', 'name': 'Scotland'}, 
    {'id': 'Bul', 'name': 'Bulgaria'}, 
    {'id': 'Pol', 'name': 'Poland'}, 
    {'id': 'Srb', 'name': 'Serbia'},
    {'id': 'Rom', 'name': 'Romania'}, 
    {'id': 'Bls', 'name': 'Belarus'}, 
    {'id': 'Slo', 'name': 'Slovenia'}, 
    {'id': 'Azb', 'name': 'Azerbaijan'}, 
    {'id': 'Cyp', 'name': 'Cyprus'}, 
    {'id': 'Kaz', 'name': 'Kazakhistan'}, 
]